# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec file for building the backend as a standalone executable.

Usage:
    cd backend
    pyinstaller backend.spec

Output: dist/backend (or backend.exe on Windows)
"""

import sys
import os

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config.yaml.example', '.'),
    ],
    hiddenimports=[
        # uvicorn 相关
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        # 数据库
        'aiosqlite',
        'sqlalchemy',
        'sqlalchemy.dialects.sqlite',
        'sqlalchemy.ext.asyncio',
        # FastAPI 依赖
        'multipart',
        'openai',
        'qdrant_client',
        'apscheduler',
        'apscheduler.schedulers.asyncio',
        'apscheduler.triggers.cron',
        'cryptography',
        # Python 标准库 - 网络/邮件
        'email',
        'email.mime',
        'email.mime.text',
        'email.mime.multipart',
        'email.mime.base',
        'email.header',
        'email.utils',
        'email.charset',
        'email.encoders',
        'email.errors',
        'email.parser',
        'email.feedparser',
        'html',
        'html.parser',
        'http',
        'http.client',
        'http.server',
        'http.cookies',
        'xml',
        'xml.etree',
        'xml.etree.ElementTree',
        'xml.parsers',
        'xml.parsers.expat',
        # Python 标准库 - 日期/时间
        'calendar',
        'datetime',
        'dateutil',
        'dateutil.parser',
        # Python 标准库 - 其他常用
        'json',
        'csv',
        'logging',
        'logging.config',
        'logging.handlers',
        'uuid',
        'decimal',
        'fractions',
        'numbers',
        'string',
        're',
        'difflib',
        'textwrap',
        'unicodedata',
        'stringprep',
        'readline',
        'rlcompleter',
        'struct',
        'codecs',
        'encodings',
        'encodings.utf_8',
        'encodings.ascii',
        'encodings.latin_1',
        'io',
        'tempfile',
        'shutil',
        'glob',
        'fnmatch',
        'linecache',
        'tokenize',
        'token',
        'keyword',
        'operator',
        'collections',
        'heapq',
        'bisect',
        'array',
        'weakref',
        'types',
        'copy',
        'pprint',
        'reprlib',
        'enum',
        'numbers',
        'math',
        'cmath',
        'random',
        'statistics',
        'itertools',
        'functools',
        'operator',
        'pathlib',
        'fileinput',
        'stat',
        'filecmp',
        'tempfile',
        'glob',
        'fnmatch',
        'linecache',
        'shelve',
        'marshal',
        'dbm',
        'sqlite3',
        'zipfile',
        'tarfile',
        'gzip',
        'bz2',
        'lzma',
        'zlib',
        'configparser',
        'netrc',
        'plistlib',
        'hashlib',
        'hmac',
        'secrets',
        'os',
        'io',
        'time',
        'argparse',
        'getopt',
        'cmd',
        'shlex',
        'subprocess',
        'sched',
        '_thread',
        'threading',
        'multiprocessing',
        'concurrent',
        'concurrent.futures',
        'asyncio',
        'contextvars',
        'contextlib',
        'abc',
        'atexit',
        'traceback',
        '__future__',
        'gc',
        'inspect',
        'site',
        'warnings',
        'dataclasses',
        'typing',
        'typing_extensions',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # 只排除确定不需要的大型库
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'PIL',
        'IPython',
        'jupyter',
        'notebook',
        'pytest',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,  # 桌面应用不显示控制台窗口
    disable_windowed_traceback=False,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='backend',
)
